PORT: ${env:PORT}
APP_ENVIRONMENT: ${env:APP_ENVIRONMENT}
OFFLINE: ${env:OFFLINE}

DB_NAME: ${env:DB_NAME}
DB_URL: ${env:DB_URL}

URL_GEOCODING: ${env:URL_GEOCODING}
API_KEY_GEOCODING: ${env:API_KEY_GEOCODING}
