service: skeleton

useDotenv: true

plugins:
  - serverless-plugin-optimize
  - serverless-offline

custom:
  serverless-offline:
    httpPort: ${env:PORT}

provider:
  name: aws
  timeout: 900
  runtime: nodejs20.x
  environment: ${file(ymls/environment.yml)}

functions: ${file(ymls/functions.yml)}
