service: serverless-chansey

useDotenv: true

plugins:
  - serverless-plugin-optimize
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 900
  environment:
    PORT: ${env:PORT}
    APP_ENVIRONMENT: ${env:APP_ENVIRONMENT}

    DB_NAME: ${env:DB_NAME}
    DB_URL: ${env:DB_URL}

    URL_GEOCODING: ${env:URL_GEOCODING}
    API_KEY_GEOCODING: ${env:API_KEY_GEOCODING}

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
